ballresponse = [
  'Yes', 'No', 'Take a wild guess...', 'Very doubtful',
  'Sure', 'Without a doubt', 'Most likely', 'Might be possible',
  "You'll be the judge", 'no... (╯°□°）╯︵ ┻━┻', 'no... baka',
  'senpai, pls no ;-;''It is certain.',
                        'It is decidedly so.',
                        'Without a doubt.',
                        'Yes - definitely.',
                        'You may rely on it.',
                        'As I see it, yes.',
                        'Most likely.',
                        'Outlook good.',
                        'Yes.',
                        'Signs point to yes.',
                        'Reply hazy, try again',
                        'Ask again later.',
                        'Better not tell you now.',
                        'Cannot predict now.',
                        'Concentrate and ask again.',
                        "Don't count on it.",
                        'My reply is no.',
                        'My sources say no.',
                        'Outlook not so good.',
                        'Very doubtful.',
                        'Aditya giri says so',
'Aditya giri says no'
]
